[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py39']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | (.*)/migrations
    | dist
  )/
)
'''
[tool.commitizen]
version = "0.8.2"
tag_format = "v$version"
version_files = [
  "pyproject.toml:version",
  "engineervix_test/__init__.py"
]
